### ISSUE TITLE
Text defaults to light gray

### ISSUE THREAD

**Issue by jaycweb** [thesparkgroup/esiason-foundation#37]
The parent theme's styles auto-apply a light gray color to body text and more specifically to certain elements (such as ordered and unordered lists). The font color when placed against a light background should be changed to #1e1e1e via child theme css.

**Comment by davidally** [comment]
Could you screenshot and example?

**Comment by jaycweb** [comment]
![a](https://user-images.githubusercontent.com/28024875/55908674-136c2a80-5ba8-11e9-9b77-b4ce0ff87f02.jpg)
